### ISSUE TITLE
Tips

### ISSUE THREAD

**Issue by SleepyLGod** [wanstle/learning#1]
You can learn something about `.gitignore`, there are some files you don't need to push to the remote repository, like some config files in the `.vscode` and some files with the suffix `.exe`.
There are some docs:  [`.gitignore`](https://git-scm.com/docs/gitignore), [`github gitignore`](https://github.com/github/gitignore), etc. And you can certainly search the corresponding gitignore templates in the Internet.
Good luck!

**Comment by wanstle** [comment]
Okyu!👌
